services:
  db:
    image: postgres
    restart: always
    env_file:
      - ./challenge/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - ./challenge/.env
    volumes:
      - .:/challenge
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data: