# Generated by Django 4.1.7 on 2023-02-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('typology', models.CharField(max_length=200)),
                ('holder', models.CharField(max_length=200)),
                ('investment', models.CharField(max_length=200)),
                ('date_admission', models.DateField()),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
